version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: gestion_rh:latest
    container_name: gestion_rh
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html:cached
      - ./vendor:/var/www/html/vendor
      - ./node_modules:/var/www/html/node_modules
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    networks:
      - gestion_rh-network

  web:
    image: nginx:1.25-alpine
    container_name: gestion_rh_web
    restart: unless-stopped
    ports:
      - "8080:80"   # accède à http://localhost:8080
    volumes:
      - ./:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - gestion_rh-network

  db:
    image: mysql:8.0
    container_name: gestion_rh_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: gestion_rh
      MYSQL_USER: gestion_rhuser
      MYSQL_PASSWORD: secret
    ports:
      # - "3306:3306"
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - gestion_rh-network

  redis:
    image: redis:7
    container_name: gestion_rh_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - gestion_rh-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: gestion_rh_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - gestion_rh-network

volumes:
  dbdata:

networks:
  gestion_rh-network:
    driver: bridge
